kumuluzee:
  name: Zvestoba JPA
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/ZvestobaDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/zvestoba
      username: postgres
      password: postgres
      max-pool-size: 20
rest-properties:
  external-services:
    ponudniki-storitev:
      #base-url: "https://aa-ponudniki-storitev.herokuapp.com/v1"
      base-url: "localhost:8081/v1"
rabbitmq:
  host: 192.168.99.100
  username: rabbit
  password: rabbit