kumuluzee:
  name: Zvestoba JPA
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/ZvestobaDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/zvestoba
      username: postgres
      password: postgres
      max-pool-size: 20